services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Smichaelsen\MelonImages\Command\:
    resource: '../Classes/Command/*'
    public: true

  Smichaelsen\MelonImages\Configuration\:
    resource: '../Classes/Configuration/*'
    public: true

  Smichaelsen\MelonImages\EventListener\:
    resource: '../Classes/EventListener/*'
    public: true

  Smichaelsen\MelonImages\Service\:
    resource: '../Classes/Service/*'
    public: true

  Smichaelsen\MelonImages\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true

  Smichaelsen\MelonImages\Command\CreateNeededCroppings:
    tags:
      - name: 'console.command'
        command: 'melon_images:createNeededCroppings'

  Smichaelsen\MelonImages\EventListener\AddCroppingConfigurationToTca:
    tags:
      - name: event.listener
        identifier: 'MelonImagesAddCroppingConfigurationToTca'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
